// Generated by gencpp from file service_demo/greeting.msg
// DO NOT EDIT!


#ifndef SERVICE_DEMO_MESSAGE_GREETING_H
#define SERVICE_DEMO_MESSAGE_GREETING_H

#include <ros/service_traits.h>


#include <service_demo/greetingRequest.h>
#include <service_demo/greetingResponse.h>


namespace service_demo
{

struct greeting
{

typedef greetingRequest Request;
typedef greetingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct greeting
} // namespace service_demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_demo::greeting > {
  static const char* value()
  {
    return "116e2074a4605229af423317e5dff099";
  }

  static const char* value(const ::service_demo::greeting&) { return value(); }
};

template<>
struct DataType< ::service_demo::greeting > {
  static const char* value()
  {
    return "service_demo/greeting";
  }

  static const char* value(const ::service_demo::greeting&) { return value(); }
};


// service_traits::MD5Sum< ::service_demo::greetingRequest> should match 
// service_traits::MD5Sum< ::service_demo::greeting > 
template<>
struct MD5Sum< ::service_demo::greetingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_demo::greeting >::value();
  }
  static const char* value(const ::service_demo::greetingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_demo::greetingRequest> should match 
// service_traits::DataType< ::service_demo::greeting > 
template<>
struct DataType< ::service_demo::greetingRequest>
{
  static const char* value()
  {
    return DataType< ::service_demo::greeting >::value();
  }
  static const char* value(const ::service_demo::greetingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_demo::greetingResponse> should match 
// service_traits::MD5Sum< ::service_demo::greeting > 
template<>
struct MD5Sum< ::service_demo::greetingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_demo::greeting >::value();
  }
  static const char* value(const ::service_demo::greetingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_demo::greetingResponse> should match 
// service_traits::DataType< ::service_demo::greeting > 
template<>
struct DataType< ::service_demo::greetingResponse>
{
  static const char* value()
  {
    return DataType< ::service_demo::greeting >::value();
  }
  static const char* value(const ::service_demo::greetingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_DEMO_MESSAGE_GREETING_H
